export const TRANSFER_CODE = 'TRANSFER_CODE';
export const RECEIVE_CODE = 'RECEIVE_CODE';
export const REQUEST_CODE = 'REQUEST_CODE';
export const SELECT_CODE = 'SELECT_CODE';
export const SUBMIT_CODE = 'SUBMIT_CODE';
export const SUBMIT_CODE_SUCCESS = 'SUBMIT_CODE_SUCCESS';

export const REQUEST_CODESMELLS = 'REQUEST_CODESMELLS';
export const RECEIVE_CODESMELLS = 'RECEIVE_CODESMELLS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
